apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: jenkins
  labels:
    app.kubernetes.io/name: nodejs-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app.kubernetes.io/name: nodejs-service
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: nodejs

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  namespace: jenkins
  labels:
    app.kubernetes.io/name: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nodejs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nodejs
    spec:
      containers:
        - name: nodejs
          image: minabasta/nodejs-app-with-dockerfile:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1024Mi
          ports:
            - containerPort: 3000
              protocol: TCP
              name: nodejs